version: '3.8'

services:
  mongodb:
    image: mongo
    command:
      - --auth
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongo-data:/data/db

  nats:
    image: nats
    container_name: nats
    ports:
      - "4222:4222"

  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    volumes:
      - zookeeper-data:/var/lib/zookeeper/data
      - zookeeper-log:/var/lib/zookeeper/log

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka-data:/var/lib/kafka/data
    ports:
      - "9092:9092"

  schema-registry:
    image: confluentinc/cp-schema-registry:latest
    depends_on:
      - kafka
      - zookeeper
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka:29092
      SCHEMA_REGISTRY_KAFKASTORE_SECURITY_PROTOCOL: PLAINTEXT
    ports:
      - "8081:8081"

  app1:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app1
    restart: on-failure
    depends_on:
      - mongodb
      - nats
      - kafka
    ports:
      - '8080:8080'
      - '9090:9090'
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.data.mongodb.host" : "mongodb",
            "spring.data.mongodb.port" : "27017",
            "nats.url" : "nats://nats:4222",
            "kafka.bootstrap-servers" : "kafka:29092",
            "spring.kafka.properties.schema.registry.url" : "http://schema-registry:8081",
            "schema.registry.url" : "http://schema-registry:8081"
          }'

  app2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app2
    restart: on-failure
    depends_on:
      - mongodb
      - nats
      - kafka
    ports:
      - '8079:8080'
      - '9089:9090'
    environment:
      SPRING_APPLICATION_JSON: '{
            "spring.data.mongodb.host" : "mongodb",
            "spring.data.mongodb.port" : "27017",
            
            "nats.url" : "nats://nats:4222",
            
            "kafka.bootstrap-servers" : "kafka:29092",
            "spring.kafka.properties.schema.registry.url" : "http://schema-registry:8081",
            "schema.registry.url" : "http://schema-registry:8081"
          }'

volumes:
  mongo-data:
  zookeeper-data:
  zookeeper-log:
  kafka-data:
